//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudMVC.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MVCstudent
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="requird")]
        public string Name { get; set; }
        [Required(ErrorMessage = "requird")]
        public string Fname { get; set; }
        [Required(ErrorMessage = "requird")]
        public string Email { get; set; }
        [Required(ErrorMessage = "requird")]

        public string Mobile { get; set; }

        [Required(ErrorMessage = "requird")]
       
        public string Description { get; set; }
    }
}
